#!/usr/bin/expect -f
set timeout 10
spawn ssh admin@11.13.20.15
expect "*password"
send "admin\r"
expect "*Redback>"
send "en\r"
expect "Password:"
send "test\r"
expect "*Redback"
send "show card\r"
expect "*Redback"
send "exit\r"