#!/usr/bin/expect -f
spawn scp /tmp/config.com root@11.13.20.15:/tmp/config.com
# expect "*password"
# send "root\r"
set timeout 10
spawn ssh admin@11.13.20.15
expect "*password"
send "admin\r"
expect "*Redback>"
send "en\r"
expect "Password:"
send "test\r"
expect "*Redback"
send "configure /tmp/config.com single-app-commit\r"
expect "*Redback"
send "exit\r"