#!/usr/bin/expect -f
spawn scp {{ local_file_path }} root@{{ ip }}
# expect "*password"
# send "root\r"
set timeout 10
spawn ssh admin@{{ ip }}
expect "*password"
send "admin\r"
expect "*Redback>"
send "en\r"
expect "Password:"
send "test\r"
expect "*Redback"
send "{{ command }}\r"
expect "*Redback"
send "exit\r"
